version: '3'
services:
  backbone:
    build: ./
    depends_on:
      - db-server
    volumes:
      - ./:/app/server
    ports:
      - "80:8000"
    links:
      - "db-server:rethinkdb"
  db-server:
    image: rethinkdb:2.3.6
    volumes:
      - ./rethinkdb_data:/data/rethinkdb_data
    ports:
      - "8080:8080"
